// ============================================================
// KnowledgeScreen — 样式对象（从 KnowledgeScreen.tsx 提取）
// ============================================================

export const styles: Record<string, React.CSSProperties> = {
  container: {
    width: '100vw',
    height: '100vh',
    backgroundColor: 'var(--bg)',
    display: 'flex',
    flexDirection: 'column',
    color: 'var(--text-primary)',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '12px 20px',
    borderBottom: '1px solid var(--border)',
    backgroundColor: 'var(--bg-elevated)',
  },
  backBtn: {
    padding: '6px 14px',
    fontSize: 13,
    color: 'var(--text-secondary)',
    backgroundColor: 'var(--bg-elevated)',
    border: '1px solid var(--border)',
    borderRadius: 6,
    cursor: 'pointer',
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
    color: 'var(--text-primary)',
    margin: 0,
    letterSpacing: 2,
  },
  searchBar: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    margin: '10px 20px',
    position: 'relative',
  },
  searchInput: {
    flex: 1,
    padding: '8px 12px',
    fontSize: 13,
    backgroundColor: 'var(--bg-elevated)',
    border: '1px solid var(--border)',
    borderRadius: 6,
    color: 'var(--text-primary)',
    outline: 'none',
  },
  clearBtn: {
    position: 'absolute',
    right: 8,
    background: 'none',
    border: 'none',
    color: 'var(--text-muted)',
    cursor: 'pointer',
    fontSize: 14,
  },
  legend: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '6px 20px',
    flexWrap: 'wrap',
    fontSize: 11,
  },
  legendTitle: { color: 'var(--text-muted)', marginRight: 4, fontWeight: 'bold' },
  legendTag: {
    display: 'flex',
    alignItems: 'center',
    gap: 2,
    padding: '2px 8px',
    borderRadius: 4,
    border: '1px solid',
    fontSize: 11,
    fontWeight: 'bold',
  },
  scrollArea: {
    flex: 1,
    overflowY: 'auto',
    padding: '0 20px 30px',
  },
  section: { marginTop: 16 },
  sectionTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    margin: '0 0 8px',
    paddingLeft: 10,
    borderLeft: '3px solid',
  },
  cardGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(220px, 1fr))',
    gap: 6,
  },
  card: {
    padding: '12px',
    backgroundColor: 'var(--bg-elevated)',
    border: '1px solid var(--border)',
    cursor: 'pointer',
    transition: 'all 0.15s',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    minHeight: 72,
  },
  cardTitle: {
    fontSize: 15,
    fontWeight: 'bold',
    color: 'var(--text-primary)',
  },
  cardBottom: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    marginTop: 8,
  },
  cardMiddle: {
    flex: 1,
  },
  protocolBadge: {
    fontSize: 12,
    fontWeight: 'bold',
    fontFamily: 'monospace',
    padding: '2px 8px',
    borderRadius: 4,
  },
  detBadge: {
    fontSize: 12,
    fontWeight: 'bold',
    fontFamily: 'monospace',
    padding: '2px 6px',
    borderRadius: 4,
  },
  chiefComplaint: {
    fontSize: 13,
    color: 'var(--text-secondary)',
    marginTop: 4,
    lineHeight: 1.4,
  },

  // ---------- 弹窗 ----------
  modalOverlay: {
    position: 'fixed' as const,
    inset: 0,
    zIndex: 1000,
    backgroundColor: 'rgba(0,0,0,0.65)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backdropFilter: 'blur(2px)',
  },
  modal: {
    width: 560,
    maxHeight: '85vh',
    backgroundColor: 'var(--bg-elevated)',
    borderRadius: 10,
    border: '1px solid var(--border)',
    display: 'flex',
    flexDirection: 'column' as const,
    overflow: 'hidden',
    boxShadow: '0 10px 40px rgba(0,0,0,0.15)',
  },
  modalHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '14px 18px',
    backgroundColor: 'var(--bg-surface)',
    borderBottom: '3px solid',
  },
  modalHeaderLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
  },
  modalProtocolBadge: {
    fontSize: 18,
    fontWeight: 900,
    fontFamily: 'monospace',
    color: '#3b82f6',
    backgroundColor: 'rgba(14, 165, 233, 0.08)',
    padding: '4px 10px',
    borderRadius: 6,
    lineHeight: 1,
  },
  modalTitle: {
    fontSize: 17,
    fontWeight: 'bold',
    color: 'var(--text-primary)',
  },
  modalSubtitle: {
    fontSize: 11,
    color: 'var(--text-secondary)',
    marginTop: 2,
  },
  modalCloseBtn: {
    padding: '4px 10px',
    backgroundColor: 'transparent',
    color: 'var(--text-muted)',
    border: '1px solid var(--border)',
    borderRadius: 4,
    cursor: 'pointer',
    fontSize: 16,
    fontWeight: 'bold',
    lineHeight: 1,
  },
  modalBody: {
    flex: 1,
    padding: '14px 18px',
    overflowY: 'auto' as const,
    display: 'flex',
    flexDirection: 'column',
    gap: 14,
  },

  // ---------- 详情区块 ----------
  detailSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
  },
  detailSectionTitle: {
    fontSize: 13,
    fontWeight: 'bold',
    color: 'var(--text-secondary)',
    borderBottom: '1px solid var(--border)',
    paddingBottom: 3,
  },
  paragraph: {
    fontSize: 13,
    color: 'var(--text-secondary)',
    lineHeight: 1.8,
    margin: 0,
  },
  list: {
    margin: 0,
    paddingLeft: 18,
  },
  listItem: {
    fontSize: 13,
    color: 'var(--text-secondary)',
    lineHeight: 1.7,
  },
  infoRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '2px 0',
  },
  infoLabel: {
    fontSize: 12,
    fontWeight: 'bold',
    color: 'var(--text-muted)',
    minWidth: 64,
  },
  infoValue: {
    fontSize: 13,
    color: 'var(--text-secondary)',
  },
}
