// ============================================================
// TitleScreen — 样式对象（从 TitleScreen.tsx 提取）
// ============================================================

export const styles: Record<string, React.CSSProperties> = {
  container: {
    width: '100vw',
    height: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'var(--bg)',
    position: 'relative',
    overflow: 'hidden',
    fontFamily: 'var(--font-body)',
    animation: 'fade-in 0.6s ease-out',
  },
  scanline: {
    position: 'absolute',
    inset: 0,
    background: 'linear-gradient(180deg, transparent 0%, rgba(22, 163, 74, 0.015) 50%, transparent 100%)',
    pointerEvents: 'none',
    animation: 'scanline-sweep 8s linear infinite',
    zIndex: 1,
  },
  ecgContainer: {
    position: 'absolute',
    bottom: '15%',
    left: 0,
    right: 0,
    pointerEvents: 'none',
    zIndex: 1,
    opacity: 0.5,
  },
  ecgSvg: {
    animation: 'ecg-glow 3s ease-in-out infinite',
  },
  ecgGroup: {
    animation: 'ecg-scroll 4s linear infinite',
  },
  cornerTL: {
    position: 'absolute',
    top: 24,
    left: 24,
    width: 30,
    height: 30,
    borderTop: '2px solid rgba(22, 163, 74, 0.2)',
    borderLeft: '2px solid rgba(22, 163, 74, 0.2)',
    zIndex: 2,
  },
  cornerTR: {
    position: 'absolute',
    top: 24,
    right: 24,
    width: 30,
    height: 30,
    borderTop: '2px solid rgba(22, 163, 74, 0.2)',
    borderRight: '2px solid rgba(22, 163, 74, 0.2)',
    zIndex: 2,
  },
  cornerBL: {
    position: 'absolute',
    bottom: 24,
    left: 24,
    width: 30,
    height: 30,
    borderBottom: '2px solid rgba(22, 163, 74, 0.2)',
    borderLeft: '2px solid rgba(22, 163, 74, 0.2)',
    zIndex: 2,
  },
  cornerBR: {
    position: 'absolute',
    bottom: 24,
    right: 24,
    width: 30,
    height: 30,
    borderBottom: '2px solid rgba(22, 163, 74, 0.2)',
    borderRight: '2px solid rgba(22, 163, 74, 0.2)',
    zIndex: 2,
  },
  content: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 6,
    zIndex: 3,
    maxWidth: 520,
    padding: '20px',
    maxHeight: '100vh',
    overflowY: 'auto',
  },
  statusBar: {
    position: 'absolute',
    top: 24,
    left: 60,
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '4px 16px',
    borderRadius: 4,
    border: '1px solid var(--border)',
    backgroundColor: 'rgba(22, 163, 74, 0.04)',
    fontFamily: 'var(--font-mono)',
    fontSize: 11,
    zIndex: 3,
  },
  statusText: {
    color: '#16a34a',
    fontWeight: 600,
    letterSpacing: 1,
  },
  statusSep: {
    color: 'var(--text-dim)',
  },
  title: {
    fontSize: 42,
    fontWeight: 800,
    color: 'var(--text-primary)',
    margin: 0,
    letterSpacing: 6,
    fontFamily: 'var(--font-mono)',
    textShadow: '0 0 30px rgba(22, 163, 74, 0.12)',
  },
  subtitle: {
    fontSize: 12,
    color: 'var(--text-muted)',
    margin: 0,
    letterSpacing: 4,
    fontFamily: 'var(--font-mono)',
    fontWeight: 500,
  },
  divider: {
    width: 220,
    height: 1,
    background: 'linear-gradient(90deg, transparent, var(--border-bright), transparent)',
    margin: '10px 0',
  },
  tagline: {
    textAlign: 'center' as const,
    color: 'var(--text-secondary)',
    fontSize: 14,
    marginTop: 4,
    letterSpacing: 2,
    fontWeight: 500,
  },
  buttonRow: {
    display: 'flex',
    gap: 10,
    alignItems: 'center',
    marginTop: 8,
  },
  startBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: 4,
    padding: '14px 56px',
    fontSize: 18,
    fontWeight: 700,
    color: '#fff',
    backgroundColor: '#dc2626',
    border: 'none',
    borderRadius: 6,
    cursor: 'pointer',
    letterSpacing: 3,
    fontFamily: 'var(--font-mono)',
    boxShadow: '0 0 20px rgba(220, 38, 38, 0.3), inset 0 1px 0 rgba(255,255,255,0.1)',
    transition: 'all 0.3s',
  },
  secondaryBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: 4,
    padding: '14px 28px',
    fontSize: 14,
    fontWeight: 600,
    color: 'var(--text-secondary)',
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    border: '1px solid var(--border)',
    borderRadius: 6,
    cursor: 'pointer',
    fontFamily: 'var(--font-mono)',
    letterSpacing: 1,
    transition: 'all 0.2s',
  },
  version: {
    fontSize: 10,
    color: 'var(--text-dim)',
    marginTop: 20,
    fontFamily: 'var(--font-mono)',
    letterSpacing: 1,
  },
}
