import { test, expect } from '@playwright/test'
test.beforeEach(async ({ page }) => {
  await page.route('**/api/tts', route => route.fulfill({ status: 503, contentType: 'application/json', body: '{"error":"test unavailable"}' }))
  await page.route('**/*.basemaps.cartocdn.com/**', route => route.abort())
})
for (const [width, height] of [[1920,1080], [1366,768], [1280,720], [1024,768], [390,844]]) {
  test(`layout and reachable controls at ${width}x${height}`, async ({ page }) => {
    await page.setViewportSize({ width, height })
    const errors: string[] = []
    page.on('pageerror', error => errors.push(error.message))
    await page.goto('/')
    await expect(page.getByRole('heading', { name: /电话这头.*希望的起点/ })).toBeVisible()
    await page.screenshot({ path: `artifacts/title-${width}.png`, fullPage: true })
    await page.getByRole('button', { name: '开始值班', exact: true }).click()
    await page.getByRole('button', { name: '接听来电', exact: true }).click()
    if (width < 960) await page.getByRole('button', { name: '工作区', exact: true }).click()
    await page.getByRole('button', { name: '确认位置', exact: true }).click()
    await page.screenshot({ path: `artifacts/workbench-${width}.png`, fullPage: true })
    if (width < 1280) await page.getByRole('button', { name: '任务卡', exact: true }).click()
    await expect(page.getByRole('button', { name: '规划救援路线', exact: true })).toBeDisabled()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
    await page.getByRole('button', { name: '暂停值班', exact: true }).click()
    await expect(page.getByRole('dialog', { name: '值班已暂停' })).toBeVisible()
    await page.getByRole('button', { name: '继续值班', exact: true }).click()
    expect(errors).toEqual([])
  })
}
test('pause, cancel, weak network, refresh and explicit handoff', async ({ page }) => {
  await page.setViewportSize({ width: 1366, height: 768 })
  await page.goto('/')
  await page.waitForTimeout(500)
  await page.clock.install()
  await page.getByRole('button', { name: '开始值班', exact: true }).click()
  await page.getByRole('button', { name: '接听来电', exact: true }).click()
  await page.getByRole('button', { name: '确认位置', exact: true }).click()
  await page.clock.runFor(2100)
  await page.getByRole('group', { name: '患者有意识吗？' }).getByRole('button', { name: '有', exact: true }).click()
  await page.getByRole('group', { name: '患者有正常呼吸吗？' }).getByRole('button', { name: '有', exact: true }).click()
  await page.getByLabel('响应优先级').selectOption('CHARLIE')
  await page.getByRole('button', { name: '规划救援路线', exact: true }).click()
  await expect(page.getByTestId('route-planner')).toBeVisible()
  for (const node of ['北城路口', '高架入口', '中心交汇点', '医院联络道', '河畔路口', '事件现场']) {
    await page.getByRole('button', { name: `选择节点 ${node}`, exact: true }).click()
  }
  await expect(page.getByRole('button', { name: '确认路线并派车', exact: true })).toBeEnabled()
  await page.clock.runFor(500)
  await page.screenshot({ path: 'artifacts/route-planning.png', fullPage: true })
  await page.getByRole('button', { name: '确认路线并派车', exact: true }).click()
  await expect(page.getByText('救护车已出发', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '设置', exact: true }).click()
  const timer = page.locator('.patient-summary time')
  const before = await timer.innerText()
  await page.clock.runFor(10000)
  await expect(timer).toHaveText(before)
  await page.getByRole('button', { name: '关闭', exact: true }).click()
  await page.getByRole('button', { name: '结束当前通话', exact: true }).click()
  await page.getByRole('button', { name: '继续当前通话', exact: true }).click()
  await expect(page.getByLabel('事发地址')).not.toHaveValue('')
  await page.reload()
  await page.getByRole('button', { name: '继续第 1 通', exact: true }).click()
  await page.getByRole('button', { name: '接听来电', exact: true }).click()
  await expect(page.getByLabel('事发地址')).toHaveValue('')
  await page.getByRole('button', { name: '确认位置', exact: true }).click()
  await page.clock.runFor(2100)
  await expect(page.getByText('离线示意图 · 不影响路线规划')).toBeVisible()
})
