import type { CSSProperties } from 'react'

export const styles: Record<string, CSSProperties> = {
  overlay: {
    position: 'fixed',
    inset: 0,
    zIndex: 1000,
    backgroundColor: 'rgba(0,0,0,0.8)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backdropFilter: 'blur(3px)',
  },
  card: {
    width: 'min(520px, calc(100vw - 24px))',
    maxHeight: '85vh',
    backgroundColor: 'var(--bg-elevated)',
    borderRadius: 10,
    border: '1px solid var(--border)',
    padding: '20px 24px',
    overflowY: 'auto',
    color: 'var(--text-primary)',
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  header: {
    fontSize: 18,
    fontWeight: 'bold',
    color: 'var(--text-primary)',
    textAlign: 'center',
    margin: 0,
  },
  totalScore: {
    textAlign: 'center',
    padding: '4px 0',
    display: 'flex',
    alignItems: 'baseline',
    justifyContent: 'center',
    gap: 6,
  },
  totalScoreValue: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#0ea5e9',
    fontFamily: 'monospace',
  },
  totalScoreLabel: {
    fontSize: 16,
    color: 'var(--text-secondary)',
    marginLeft: 4,
  },
  outcomeBox: {
    border: '1px solid',
    borderRadius: 8,
    padding: '12px 14px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 5,
  },
  outcomeBadge: {
    fontSize: 11,
    fontWeight: 900,
    letterSpacing: 0.4,
  },
  outcomeTitle: {
    fontSize: 18,
    fontWeight: 800,
    color: 'var(--text-primary)',
  },
  patientStatus: {
    fontSize: 13,
    fontWeight: 700,
    color: 'var(--text-primary)',
  },
  consequence: {
    fontSize: 12,
    color: 'var(--text-secondary)',
    lineHeight: 1.5,
  },
  breakdownRow: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 4,
  },
  breakdownItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  breakdownLabel: {
    fontSize: 11,
    color: 'var(--text-muted)',
    minWidth: 56,
    textAlign: 'right' as const,
  },
  breakdownBarTrack: {
    flex: 1,
    height: 8,
    backgroundColor: 'var(--border-light)',
    borderRadius: 4,
    overflow: 'hidden',
  },
  breakdownBarFill: {
    height: '100%',
    borderRadius: 4,
    transition: 'width 0.6s ease',
  },
  breakdownValue: {
    fontSize: 11,
    fontWeight: 'bold',
    fontFamily: 'monospace',
    minWidth: 40,
  },
  penaltyRow: {
    textAlign: 'center' as const,
    fontSize: 12,
    color: '#ff6b6b',
    padding: '2px 0',
  },
  divider: {
    height: 1,
    backgroundColor: 'var(--border-light)',
    margin: '2px 0',
  },
  detailGrid: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 4,
  },
  detailItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    fontSize: 12,
    padding: '2px 4px',
  },
  detailLabel: {
    color: 'var(--text-muted)',
    minWidth: 90,
  },
  detailValue: {
    fontSize: 12,
    fontWeight: 'bold',
    fontFamily: 'monospace',
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#d97706',
    borderBottom: '1px solid var(--border)',
    paddingBottom: 3,
    marginTop: 4,
  },
  judgmentList: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 4,
  },
  judgmentRow: {
    padding: '6px 8px',
    borderRadius: 6,
    border: '1px solid',
    backgroundColor: 'var(--bg-input)',
  },
  judgmentQuestion: {
    fontSize: 11,
    color: 'var(--text-secondary)',
    marginBottom: 2,
  },
  judgmentChoices: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: 4,
  },
  narrativeBox: {
    marginTop: 4,
    padding: '8px 10px',
    backgroundColor: 'var(--bg-input)',
    borderRadius: 6,
    border: '1px solid var(--border-light)',
  },
  narrativeText: {
    fontSize: 12,
    color: 'var(--text-muted)',
    lineHeight: 1.6,
    fontStyle: 'italic' as const,
  },
  reviewBox: {
    padding: '2px 0 0',
  },
  reviewPoint: {
    fontSize: 12,
    color: 'var(--text-primary)',
    lineHeight: 1.5,
    padding: '3px 0 3px 14px',
  },
  nextBtn: {
    padding: '12px 24px',
    backgroundColor: '#dc2626',
    color: '#fff',
    border: 'none',
    borderRadius: 6,
    fontSize: 15,
    fontWeight: 'bold',
    cursor: 'pointer',
    fontFamily: 'inherit',
    alignSelf: 'center' as const,
  },
}
