import type { CSSProperties } from 'react'

export const styles: Record<string, CSSProperties> = {
  overlay: {
    position: 'fixed',
    inset: 0,
    zIndex: 1000,
    backgroundColor: 'var(--scrim-strong)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backdropFilter: 'blur(3px)',
  },
  card: {
    width: 'min(520px, calc(100vw - 24px))',
    maxHeight: '85vh',
    backgroundColor: 'var(--bg-raised)',
    borderRadius: 'var(--radius-xl)',
    border: '1px solid var(--line)',
    padding: '20px 24px',
    overflowY: 'auto',
    color: 'var(--text)',
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  header: {
    fontSize: 'var(--fs-subtitle)',
    fontWeight: 'var(--fw-bold)',
    color: 'var(--text)',
    textAlign: 'center',
    margin: 0,
  },
  totalScore: {
    textAlign: 'center',
    padding: '4px 0',
    display: 'flex',
    alignItems: 'baseline',
    justifyContent: 'center',
    gap: 6,
  },
  totalScoreValue: {
    fontSize: 'var(--fs-heading-lg)',
    fontWeight: 'var(--fw-bold)',
    color: 'var(--accent)',
    fontFamily: 'var(--font-mono)',
  },
  totalScoreLabel: {
    fontSize: 'var(--fs-body)',
    color: 'var(--text-2)',
    marginLeft: 4,
  },
  outcomeBox: {
    border: '1px solid',
    borderRadius: 'var(--radius-lg)',
    padding: '12px 14px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 5,
  },
  outcomeBadge: {
    fontSize: 'var(--fs-small)',
    letterSpacing: 0.4,
  },
  outcomeTitle: {
    fontSize: 'var(--fs-body)',
    fontWeight: 'var(--fw-extrabold)',
    color: 'var(--text)',
  },
  patientStatus: {
    fontSize: 'var(--fs-body-sm)',
    fontWeight: 'var(--fw-bold)',
    color: 'var(--text)',
  },
  consequence: {
    fontSize: 'var(--fs-caption)',
    color: 'var(--text-2)',
    lineHeight: 1.5,
  },
  breakdownRow: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 4,
  },
  breakdownItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  breakdownLabel: {
    fontSize: 'var(--fs-small)',
    color: 'var(--text-3)',
    minWidth: 56,
    textAlign: 'right' as const,
  },
  breakdownBarTrack: {
    flex: 1,
    height: 8,
    backgroundColor: 'var(--line-soft)',
    borderRadius: 'var(--radius-sm)',
    overflow: 'hidden',
  },
  breakdownBarFill: {
    height: '100%',
    borderRadius: 'var(--radius-sm)',
    transition: 'width 0.6s ease',
  },
  breakdownValue: {
    fontSize: 'var(--fs-small)',
    fontWeight: 'var(--fw-bold)',
    fontFamily: 'var(--font-mono)',
    minWidth: 40,
  },
  penaltyRow: {
    textAlign: 'center' as const,
    fontSize: 'var(--fs-caption)',
    color: 'var(--danger)',
    padding: '2px 0',
  },
  divider: {
    height: 1,
    backgroundColor: 'var(--line-soft)',
    margin: '2px 0',
  },
  detailGrid: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 4,
  },
  detailItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    fontSize: 'var(--fs-caption)',
    padding: '2px 4px',
  },
  detailLabel: {
    color: 'var(--text-3)',
    minWidth: 90,
  },
  detailValue: {
    fontSize: 'var(--fs-caption)',
    fontWeight: 'var(--fw-bold)',
    fontFamily: 'var(--font-mono)',
  },
  sectionTitle: {
    fontSize: 'var(--fs-caption)',
    fontWeight: 'var(--fw-bold)',
    color: 'var(--warning)',
    borderBottom: '1px solid var(--line)',
    paddingBottom: 3,
    marginTop: 4,
  },
  judgmentList: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 4,
  },
  judgmentRow: {
    padding: '6px 8px',
    borderRadius: 'var(--radius-md)',
    border: '1px solid',
    backgroundColor: 'var(--bg-input)',
  },
  judgmentQuestion: {
    fontSize: 'var(--fs-small)',
    color: 'var(--text-2)',
    marginBottom: 2,
  },
  judgmentChoices: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: 4,
  },
  narrativeBox: {
    marginTop: 4,
    padding: '8px 10px',
    backgroundColor: 'var(--bg-input)',
    borderRadius: 'var(--radius-md)',
    border: '1px solid var(--line-soft)',
  },
  narrativeText: {
    fontSize: 'var(--fs-caption)',
    color: 'var(--text-3)',
    lineHeight: 1.6,
    fontStyle: 'italic' as const,
  },
  reviewBox: {
    padding: '2px 0 0',
  },
  reviewPoint: {
    fontSize: 'var(--fs-caption)',
    color: 'var(--text)',
    lineHeight: 1.5,
    padding: '3px 0 3px 14px',
  },
  nextBtn: {
    padding: '12px 24px',
    backgroundColor: 'var(--danger)',
    color: 'var(--on-danger)',
    border: 'none',
    borderRadius: 'var(--radius-md)',
    fontSize: 'var(--fs-body-lg)',
    fontWeight: 'var(--fw-bold)',
    cursor: 'pointer',
    fontFamily: 'inherit',
    alignSelf: 'center' as const,
  },
}
